config-version: 2

# Placeholders:
# {message} - the chat message
# {name} - the player's name
# {displayname} - the player's display name / nickname
# {world} - the world name of the player's current world
# {prefix} - the player's highest priority prefix
# {suffix} - the player's highest priority suffix
# {prefixes} - the player's prefixes sorted by the highest priority
# {suffixes} - the player's suffixes sorted by the highest priority
# {username-color} - the player's or the group's username color
# {message-color} - the player's or the group's message color

# WARNING: Prefixes, Suffixes, message-color etc. needs to be Minimessage Colorcodes and not Legacy!

# To reload the configuration, run '/lpc reload' command. Make sure you have the 'lpc.reload' permission assigned.
# More information can be found at the GitHub Wiki.
chat-format: "{prefix}{name}<dark_gray> »<reset> {message}"

# Set the format per group.
# Note: Option for more advanced users. Remove comments to run.
group-formats:
#  default: "[default] {name}<dark_gray> »<reset> {message}"
#  admin: "[admin] {name}<dark_gray> »<reset> {message}"

# Set the format per track
# Note: Group formatting takes priority over track formatting, ensure user isn't in a group with corresponding format to apply track format
track-formats:
#  staff_track: "[staff] {name}<dark_gray> »<reset> {message}"
#  donator_track: "{donator_rank} {name}<dark_gray> »<reset> {message}"

# Should the [item] placeholder be enabled
use-item-placeholder: true

# Editing Reload-message
reload-message: "<green>Reloaded LPC Configuration!"


afk-timeout: 30

endabled: true

api-key: ""

# Optional: The prompt template for the AI (use %s for the user's question)
prompt-template: "You are an AI assistant responding to questions within a Minecraft chat environment. 
                  Please keep your answers concise, informative, and relevant to the context. 
                  Do not include images, links, or any other content that cannot be displayed in chat.
                  Question: %s"

# Optional: The API URL (only change if using a custom endpoint)
api-url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent"

# Name of the bot when it broadcasts the response
bot-name: "Notch"

# When false, the players question and response from AI is broadcast to whole server.
# When true, it won't display player's questions and will privately message the player who asked
private-questions: false

message:
  presentOnJoin: false

  text:
    - "&b&lJoin our discord! (Not done)"

  textHover: "Click to go to our discord"

  textClick: "https://discord.gg/???"

sound:
  enabled: true
  value: "ENTITY_EXPERIENCE_ORB_PICKUP"

rules:
  - "&e1. No griefing!"
  - "&e2. Be respectful to others."
  - "&e3. No spamming in chat."
  - "&e4. Follow staff instructions."

# ELYTRA DROP PERCENTAGE
# This will apply to all drops
# (Default = 100; Min = 1; Max = 100)
elytra_drop_percentage: 50

# ELYTRA DROP AMOUNT
# This will apply to all drops
# (Default = 1; Min = 1; Max = 3)
elytra_drop_amount: 1

tablist:
  header:
    - '<text>'
    - '<text>'
  hooder:
    - '<text>'
    - '<text>'